name: Publish to Chrome Web Store

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Zip files
        run: zip -r extension.zip dist/
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: ${{ github.event.head_commit.message }}
          files: extension.zip
          name: Release ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
